#logging日志
logging:
  config: classpath:log4j2.xml
#数据库
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@localhost:1521:test
    username: test
    password: test
    driver-class-name: oracle.jdbc.OracleDriver
#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.**.entity
  configuration:
    cache-enabled: false
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID
    id-type: 1
    key-generator: com.baomidou.mybatisplus.extension.incrementer.OracleKeyGenerator
    #如果插件版本是3.0-gamma这个选项必须配置,否则会nullPoint
    #mybatis-plus.global-config.db-config.db-type=oracle
    #配置JdbcTypeForNull, oracle数据库必须配置
#应用部署
server:
  servlet:
    context-path: /sy
  port: 8080